name: Java CI with Maven

on:
  push:
    branches: [ master ]   # Execute on push to master branch
  pull_request:
    branches: [ master ]   # Execute on pull requests to master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up JDK 11
    #   uses: actions/setup-java@v2
    #   with:
    #     java-version: '11'

    - name: Build with Maven
      run: mvn -B clean package

    - name: Execute Tests
      run: mvn test -Dtest=commonMethods.TestNgXml
