name: Java Selenium Tests

on:
  push:
    branches: [master]   # Execute on push to master branch
  pull_request:
    branches: [master]   # Execute on pull requests to master branch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Chrome WebDriver
      uses: nanasess/setup-chromedriver@v1

    - name: Set up Firefox WebDriver
      uses: nanasess/setup-geckodriver@v1

    - name: Build and Test with Maven
      run: mvn -B verify

    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports
