name: Selenium Tests

on:
  # push:
  #   branches: [master]   # Execute on push to master branch
  # pull_request:
  #   branches: [master]   # Execute on pull requests to master branch

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CHROME_HEADLESS: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Debug Java Version
      run: java -version

    - name: Set up WebDriver
      run: |
        CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -qP /tmp/ "https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip"
        unzip -o /tmp/chromedriver_linux64.zip -d /tmp/
        sudo mv /tmp/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        firefox --version  # Ensure Firefox is available
        geckodriver --version  # Ensure GeckoDriver is available

    - name: Build and Test with Maven
      run: mvn -B verify
