name: Selenium Execution

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  execute_selenium_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Adjust Java version as per your requirement
      
      - name: Install Maven
        run: sudo apt-get install maven -y # Install Maven
      
      - name: Run Selenium Tests
        run: mvn clean test # Execute Selenium tests using Maven
